/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateUserRequest {
  nickname: string;
  /**
   * Optional: users can register by nickname only
   */
  password?: string;
  role: CreateUserRequest.RoleEnum;
}
export namespace CreateUserRequest {
  export const RoleEnum = {
    ADMIN: 'ADMIN',
    ML_ENGINEER: 'ML_ENGINEER',
    REVIEWER: 'REVIEWER',
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
}
