/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateArtifactRequest {
  name: string;
  type: CreateArtifactRequest.TypeEnum;
  path: string;
  sizeBytes: number;
}
export namespace CreateArtifactRequest {
  export const TypeEnum = {
    MODEL: 'MODEL',
    IMAGE: 'IMAGE',
    DATASET: 'DATASET',
    LOG: 'LOG',
    OTHER: 'OTHER',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
