/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateMetricRequest } from './create-metric-request';

export interface CreateMetricsRequest {
  metrics: Array<CreateMetricRequest>;
}
