/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateProjectRequest {
  name: string;
  description?: string;
  /**
   * ID of the initial project owner
   */
  ownerId: string;
}
