/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MetricResponse {
  id?: string;
  runId?: string;
  name?: string;
  value?: number;
  step?: number;
  recordedAt?: string;
}
