/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ModelVersionResponse {
  id?: string;
  projectId?: string;
  artifactId?: string;
  version?: number;
  state?: ModelVersionResponse.StateEnum;
  createdAt?: string;
  promotedAt?: string;
}
export namespace ModelVersionResponse {
  export const StateEnum = {
    NEW: 'NEW',
    STAGING: 'STAGING',
    PRODUCTION: 'PRODUCTION',
    ARCHIVED: 'ARCHIVED',
  } as const;
  export type StateEnum = (typeof StateEnum)[keyof typeof StateEnum];
}
