/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RunResponse {
  id?: string;
  experimentId?: string;
  authorId?: string;
  name?: string;
  status?: RunResponse.StatusEnum;
  createdAt?: string;
  startedAt?: string;
  finishedAt?: string;
}
export namespace RunResponse {
  export const StatusEnum = {
    CREATED: 'CREATED',
    RUNNING: 'RUNNING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
