/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RunResponse } from './run-response';

export interface RunSliceResponse {
  items?: Array<RunResponse>;
  hasNext?: boolean;
  nextCursor?: string;
}
