/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateUserRequest {
  nickname: string;
  role: UpdateUserRequest.RoleEnum;
}
export namespace UpdateUserRequest {
  export const RoleEnum = {
    ADMIN: 'ADMIN',
    ML_ENGINEER: 'ML_ENGINEER',
    REVIEWER: 'REVIEWER',
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
}
