/**
 * Experiment Tracking Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserResponse {
  id?: string;
  nickname?: string;
  role?: UserResponse.RoleEnum;
  createdAt?: string;
}
export namespace UserResponse {
  export const RoleEnum = {
    ADMIN: 'ADMIN',
    ML_ENGINEER: 'ML_ENGINEER',
    REVIEWER: 'REVIEWER',
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
}
